### ISSUE TITLE
XMLHttpRequest for environments which don't have it

### ISSUE THREAD

**Issue by GabrielBoehme13** [lobanov/elm-taskport#1]
I'd like to use this in Elm programs for some Javascript environments (Deno, Scriptable for iOS) where no XMLHttpRequest constructor exists. Currently, taskport.js appears to require an already-existing XMLHttpRequest in its environment. Can your documentation address this, and (if possible) point to an existing "mock" XMLHttpRequest that could be loaded into those environments prior to loading taskport.js?

**Comment by lobanov** [comment]
I just released version 1.0.3, which supports environments without XMLHttpRequest. In fact there is a rudimental regression test pack using Node as part of the build. Check out the README for additional installation instructions. I only tested it in Node though and would be great to know if it works in others.
